---
title: "introduction"
author: "Grigor Dimitrov"
date: "November 19, 2016"
output: pdf_document
---

<!-- soft vs. hard, introduce market research, focus on soft  -->
In economics, often the decision-making process relies both on 'soft factors' and 'hard numbers' [@Baillonpub]. The hard numbers are objective quantitative measurements, while the soft factors refer to beliefs, opinions, expectations, etc. that are subjective. Subjective data is heavily used to understand individuals' behavior, attitude, intentions and choices in many different domains, including governmental institutions and businesses @prelec2004bayesian. One specific domain is opinion-taking for market research purposes, which again relies heavily on subjective data gathered through surveys from panels of respondents. However, subjective data reliability depends on "its quality at the source - the thought process of an individual respondent" [@prelec2004bayesian]. To provide solid and credible recommendations to businesses, market researchers, who use surveys as a proxy of their decisions, crucially depend on respondents' trustworthiness.

<!-- What is conjoint  -->

One of the widely used research methodologies for the past four decades is the conjoin methodology. It has been employed in many domains such as market research, policy making, exploring optimal pricing of products, new product development, segmentation, product positioning, etc. [@ding2005incentive]. It is a broad methodology for presenting and analyzing products, services or policies. Using conjoint analysis researchers are able to elicit respondents' utilities of different characteristics of a product, service or policy. Those utilities are estimated based on data from respondents' simultaneous evaluation of components configurations across different attributes levels of a product, service or policy, also referred to as stimuli [@green2001thirty; @green1978conjoint]. Essentially, respondents are making trade-offs within a given set of product characteristics and state their preferences for the different stimuli. In the estimation process researchers are able to elicit respondents' utilities based on those trade-offs on an individual level as well as aggregating the utilities in the sample.

<!-- Conjoint problems  -->

Data collection is typically done in hypothetical settings, however, there has been a growing concern amongst market research practitioners regarding the usage of hypothetical approaches due to insufficient confidence in respondents' truthful answers' [@gittelmanrules; @puleston2012dimensions; @toubia2012measuring]. Such settings do not provide respondents sufficient incentives to carefully and honestly indicate their preferences [@ding2005incentive], respondents are not given neither incentive nor penalty to truthfully state their preferences. Hence, there could be a discrepancy between respondents' stated preferences and their real-life behavior @ding2005incentive. In an attempt to account for those concerns, the academia has been exploring the application of incentive-compatible mechanisms within the preference measurement techniques, including conjoint analysis [@ding2005incentive; @ding2007incentive; @dong2010simple; @toubia2012measuring]. @ding2005incentive rewarded respondents with their actual choice at the end of the conjoint exercise, showing that this incentive-compatible mechanism increases the external validity of the data. Furthermore, @toubia2012measuring successfully implemented incentive-compatible scheme within a choice-based conjoint exercise that showed promising results on respondents' engagement <!-- measured with eye-tracking -->. However, there are three main disadvantages related to using those methods. First, when it comes to new product development, as in @ding2005incentive, rewarding respondents with their actual choice is infeasible. Second, from an implementation standpoint, using @toubia2012measuring method requires a complex altering of the conjoint methodology in order to apply in the incentive compatibility. Third, from respondent standpoint again in @toubia2012measuring method, requires respondents understanding of the "conjoint-poker" rules in order to maximize their pay-off rather than just making choices between alternatives. I introduce an application of an incentive-compatible methodology which can account for those disadvantages - Bayesian truth serum [@prelec2004bayesian]. Bayesian truth serum can be applied in a hypothetical setting, it doesn't alter the conjoint methodology and it is relatively easier to be understood by the respondents.  

<!-- incentive compatibility -->

In 2004, Drazen Prelec introduces a new incentive-compatible mechanism called the Bayesian truth serum (hereafter BTS) @prelec2004bayesian. Essentially BTS is a method for eliciting respondents' subjective answers and meta-knowledge (i.e. knowledge of what other people know). Prelec argues that under the BTS condition respondents are acting as if they are being evaluated by an "omni-center in possession of the truth".  The method works in an absence of verifiable truth.  The method is based on a scoring system that takes into account respondents' answers as well as their probabilistic predictions about the distribution of answers within a given sample. BTS rewards truthful answers by assigning them high scores which will accordingly result in higher payoffs. The high scores are computed using both respondent's personal answer and their prediction about the distribution of others' answers. More precisely, high scores are given to an answer whose actual frequency is higher than its predicted frequency. Such an answer is referred to as "surprisingly common". For instance, if an answer is endorsed by 25% of the sample and its predicted frequency obtained from the same sample is 20%, it will be regarded as "surprisingly common" and given a high score. The method awards truthful responses for both rare and widely shared answers e.g. it does not depend on consensus as a norm for truth-telling. The method doesn't require respondents to understand any details of the scoring rule apart from the fact that it is being applied, making it easier to be applied in practice. As BTS is a relatively new methodology, it has not been employed widely, however, the results so far have been positive in terms of its validity [@weaver2013creating;  @john2012measuring ]

<!-- I will introduce -->

In this paper, I will adapt BTS to provide incentives for respondents to reveal their true preferences in a conjoint analysis of a new service development. @golbeck2016user found that on average users of social media applications, such as Facebook, are concerned about their privacy and are not well informed regarding the access of data that are given to third party applications. At the same time, users consciously neglect the terms and conditions related to data privacy on different websites. Given the fact that data privacy is a sensitive topic and at the same time users tend to ignore the general terms and conditions of a privacy policy, respondents may give socially desirable answers and misreport their true preferences @krumpal2013determinants. In this study, I will employ BTS to evaluate respondents' preferences towards a new hypothetical service that aims to buy out individuals' online private data. I will jointly evaluate the effect of several factors on the probability of individuals to enroll in that service. The factors, also the main components of this service, are the following: first, devices to which individuals would be willing to grant access to; second, the extent of the collected data; third, the monetary amount individuals are willing to accept in order to share their data. Conjoint analysis is dependent on the truthfulness of the subjective data, thus creating incentives for "truthful" responses with BTS could potentially reduce problems in regards to truthful revelation and ultimately improve the data quality.

<!-- Motivation -->

The motivation of this paper lays in the improvement of conjoint analysis reliability with an application of an incentive-compatible methodology, the BTS. The main objective of the paper is to explore whether the BTS can prove itself to be a superior truthful elicitation technique in comparison to the regular hypothetical conjoint setting. Furthermore, I will explore whether the BTS can prove itself to be a reliable method, applicable to conjoint analysis when truthful answers are not observed during the time of the research.

The main research question is as follows: 

>Can the BTS improve the choice based conjoint data quality?

To my best knowledge, no research has explored improving the reliability of choice based conjoint utilizing the BTS. One of the research's contributions research will be to complement the emerging stream of literature exploring how the external validity of conjoint analysis can be improved using an incentive-compatible method. Moreover, the paper will contribute to BTS's application in preference measurement methodologies. 

The paper is structured as follows. Firstly, the literature review section introduces in details conjoin analysis and BTS. I will additionally explore current limitations concerning online data collection. Based on the literature review section, I will develop my hypotheses. Secondly, in the methodology section, I will describe the data collection and analysis procedures regarding conjoint analysis and the BTS scoring system. Next, the result section describes a detailed analysis of the main results and findings. Finally, I will discuss the results, the main contributions and implications for both practitioners and academia and the main limitations of the study.
